# Generated by Django 4.2.7 on 2023-11-29 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelimport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceldata',
            name='data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
